language: python
python:
- '3.6'
- '3.7'
- '3.8'
services:
- docker

install:
- pip install -r requirements.txt
script:
- pycodestyle fdbk
- pylint -E --enable=invalid-name,unused-import,useless-object-inheritance fdbk
- docker run -dp 8000:8000 --name=dynamo amazon/dynamodb-local
- coverage run --branch --source fdbk/ -m unittest discover -s tst/
- coverage report -m
- docker rm -f dynamo

deploy:
  provider: pypi
  user: __token__
  password:
    secure: AYtFiggyOquEbtuui8aXTXgIXoxpBpek2J9+FH09l1rUDdNZYx0S42dGW/2OfbzL8qA0du/65Nb5iPvP+W+nXfJ6Q2zSloxUZppj6yNl/6kcylHHONZZR3FrcVk3OIqOMH1dw1H6qy27kKFbPh0bHP3zTrANy+VrheLr7dIycuIMZJ+hP92pj22Ume6L9C6N9oO/NiLhe0XQQq2ppbJBeCNxEKW/E4SwUHqtnAEBl4uui48zx+lUiW1GJG8ZDRdHX0qbIVDNaYTvhEXM4ijIjTyW3V6ihmJy+OlTrxLZLEyy8GZiZo1Clt/WbZ8AlndzO1k31KdAM/AfGGhzbM4xNA3fbendJ+2Zycxvez28wESQ4BG0TZ3JF7vtroQ6PhmnF43hN7aqNtfCT9duQQKQ0FheuUgvvRvEzOKCbjCvi1KL2OWLshnZCLfVyOtsGoz55qEPBZCh8Hus5/Kl/otoiyvhHmGBGwDG/adaeLNmfJunfCdcImrwnS0oNxb8maEnsCJZ6CXd880ZOVtF6V0uKdk2l5BI02F1iCMHWKyaqEVO5HSMIg9e97u4XeA7ge24oq3lyd7dGCGA+rZmUXYPsbqWn0YvelQzZtIE8npwHqlptuYO+UNUpurUuirYirNEMOGiRg3FEk4pFAzfn03Q82yIpLdKN9pnV/k7YSpGeq0=
  on:
    tags: true
    python: 3.7